homepage:
    pattern:  /
    defaults: { _controller: phpBBStatusSiteBundle:Default:index }

site:
    pattern: /site/{slug}
    defaults: { _controller: phpBBStatusSiteBundle:Default:site }

contact:
    pattern: /contact
    defaults: { _controller: phpBBStatusSiteBundle:Default:contact }

purge:
    pattern: /purge/
    defaults: { _controller: phpBBStatusSiteBundle:Default:purge }

api_warning:
    pattern: /api/downtime-warning/
    defaults: { _controller: phpBBStatusSiteBundle:Api:warning }
