homepage:
    pattern:  /
    defaults: { _controller: phpBBStatusSiteBundle:Default:index }

site:
    pattern: /site/{slug}
    defaults: { _controller: phpBBStatusSiteBundle:Default:site }

contact:
    pattern: /contact
    defaults: { _controller: phpBBStatusSiteBundle:Default:contact }

purge:
    pattern: /purge/
    defaults: { _controller: phpBBStatusSiteBundle:Default:purge }

api_warning:
    pattern: /api/downtime-warning/
    defaults: { _controller: phpBBStatusSiteBundle:Api:warning }

phpBBStatusSiteBundle_admin_user:
    resource: "@phpBBStatusSiteBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user

phpBBStatusSiteBundle_admin_sites:
    resource: "@phpBBStatusSiteBundle/Resources/config/routing/sites.yml"
    prefix:   /admin/sites

phpBBStatusSiteBundle_admin_checks:
    resource: "@phpBBStatusSiteBundle/Resources/config/routing/checks.yml"
    prefix:   /admin/checks

phpBBStatusSiteBundle_admin_overides:
    resource: "@phpBBStatusSiteBundle/Resources/config/routing/overides.yml"
    prefix:   /admin/overides

phpBBStatusSiteBundle_admin_updates:
    resource: "@phpBBStatusSiteBundle/Resources/config/routing/updates.yml"
    prefix:   /admin/updates
