<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121109165235 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE overides ADD update_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE overides ADD CONSTRAINT FK_E00CC138D596EAB1 FOREIGN KEY (update_id) REFERENCES updates (id)");
        $this->addSql("CREATE INDEX IDX_E00CC138D596EAB1 ON overides (update_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE overides DROP FOREIGN KEY FK_E00CC138D596EAB1");
        $this->addSql("DROP INDEX IDX_E00CC138D596EAB1 ON overides");
        $this->addSql("ALTER TABLE overides DROP update_id");
    }
}
