<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121109154627 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE sites_overides (sites_id INT NOT NULL, overides_id INT NOT NULL, INDEX IDX_FDA711737838E496 (sites_id), INDEX IDX_FDA71173976EDBDC (overides_id), PRIMARY KEY(sites_id, overides_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE overides_sites (overides_id INT NOT NULL, sites_id INT NOT NULL, INDEX IDX_E9506D4C976EDBDC (overides_id), INDEX IDX_E9506D4C7838E496 (sites_id), PRIMARY KEY(overides_id, sites_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE sites_overides ADD CONSTRAINT FK_FDA711737838E496 FOREIGN KEY (sites_id) REFERENCES sites (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE sites_overides ADD CONSTRAINT FK_FDA71173976EDBDC FOREIGN KEY (overides_id) REFERENCES overides (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE overides_sites ADD CONSTRAINT FK_E9506D4C976EDBDC FOREIGN KEY (overides_id) REFERENCES overides (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE overides_sites ADD CONSTRAINT FK_E9506D4C7838E496 FOREIGN KEY (sites_id) REFERENCES sites (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE overides DROP site_id");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE sites_overides");
        $this->addSql("DROP TABLE overides_sites");
        $this->addSql("ALTER TABLE overides ADD site_id INT NOT NULL");
    }
}
